apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-app.fullname" . }}-config
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.config.db_host | quote }}
  DB_NAME: {{ .Values.config.db_name | quote }}
